### ISSUE TITLE
Region of Interest Per Channel data

### ISSUE THREAD

**Issue by bvnayak** [planetarypy/pdsview#27]
pdsview should display channel wise statistics for ROI chosen by user.

It works correctly only if user selects more than 2 rows.

**Comment by bvnayak** [comment]
This shows ROI with 2 rows and multiple columns.
![screen shot 2015-08-27 at 12 24 18 pm](https://cloud.githubusercontent.com/assets/11728474/9530756/938b1884-4cb6-11e5-942d-3c35a6dfedbe.png)

This shows ROI with 3 rows and just 1 column.
![screen shot 2015-08-27 at 12 25 28 pm](https://cloud.githubusercontent.com/assets/11728474/9530783/c130457a-4cb6-11e5-9831-176645c79bcb.png)

**Comment by percurnicus** [comment]
This is fixed in #28. See below
![screen shot 2015-08-31 at 1 37 04 pm](https://cloud.githubusercontent.com/assets/12278722/9589778/8114f3f0-4fe5-11e5-8ff2-c572c1464216.png)
![screen shot 2015-08-31 at 1 37 28 pm](https://cloud.githubusercontent.com/assets/12278722/9589781/84b0d6b4-4fe5-11e5-8d52-74819d6d1424.png)

**Comment by godber** [comment]
@bvnayak please double check that this is resolved in https://github.com/planetarypy/pdsview/pull/28.

Close if its done.

**Comment by percurnicus** [comment]
Fixed in #28
